# Constants
DEFAULT_NODE_PORT = 8001
DEFAULT_BROADCAST_PORT = 8255

# Operation codes
FIND_SUCCESSOR = 1
FIND_PREDECESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
CHECK_NODE = 6
CLOSEST_PRECEDING_FINGER = 7
STORE_KEY = 8
RETRIEVE_KEY = 9
NOT_ALONE_NOTIFY = 10
REVERSE_NOTIFY = 11
GET_LEADER = 12
DISCOVER = 13
ENTRY_POINT = 14