# Constants used in database
END = 0
OK = 1
PULL_REPLICATION = 2
PUSH_DATA = 4
FETCH_REPLICA = 8
# PUSH_REPLICATION = 3

PUSH_THIS_REPLICA = 6
PUSH_DELETE_THIS_REPLICA = 7

# tags
REPLICATE_STORE_TAG = 11
REPLICATE_APPEND_FILE = 12
REPLICATE_DELETE_TAG = 13
REPLICATE_REMOVE_FILE = 14
